# admin/config.yml
backend:
  name: github
  repo: matiasaguetti/Ecos-del-C-rculo-Eterno   # <--- tu repo
  branch: main                                  # <--- cambia si tu rama principal no es 'main'
  auth_scope: repo
  client_id: "Ov23lia6OkV75jppl3Mo"             # <--- tu Client ID insertado

local_backend: false

media_folder: "assets/uploads"   # ruta en el repo donde se guardan las imágenes subidas
public_folder: "/assets/uploads" # ruta pública usada por el sitio

publish_mode: "editorial_workflow" # crea PRs en vez de commits directos (recomendado)

collections:
  - name: "aventureros"
    label: "Aventureros"
    folder: "content/aventureros"
    create: true
    slug: "{{slug}}/index"
    sortable_fields: ["title", "date"]
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Resumen", name: "summary", widget: "text" }
      - { label: "Biografía (Markdown)", name: "body", widget: "markdown" }
